### PR TITLE
pweave mode added

### PR DESCRIPTION
**Pull request by ndvanforeest**
I find the literate programming program Pweave (http://mpastell.com/pweave/examples/index.html)  very handy. Nicer yet is to have the python code in a pweave file beautified.  I tested the PR on the pweave file http://mpastell.com/pweave/_downloads/FIR_design_verb.texw, and it runs perfectly. 

Black runs automatically in my emacs when I save a file. I don't know whether you like the small changes black made in blacken-docs.py.  If you don't, I'll make another pull request

### CODE REVIEW

**Comment by asottile** [comment]
in general you should not touch other people's formatting

**Comment by ndvanforeest** [comment]
Of course, you are completely right. But here the changes came from black itself. This made me doubt what would be best.

**Comment by asottile** [comment]
> Of course, you are completely right. But here the changes came from black itself. This made me doubt what would be best.

should have been clear then that I don't use black :P

**Comment by ndvanforeest** [comment]
😊

**Pull request closed without merging**
